theme = "light"

server_address = "127.0.0.1"
server_port = 6603

external_server = false

library =  ["/home/michael/ExperimentBox/ouverture/dev/Library"]

database_dir = "/home/michael/ExperimentBox/ouverture/dev/db"
database_port = 6604

background=false
